services:
  nicotine:
    image: hockeygoalie35/nicotine-novnc-rpi:arm64 #Or armv7 for 32bit
    container_name: nicotine
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/pi/Appdata/nicotine/data:/data
      - /home/pi/Appdata/nicotine/data:/data/.local/share/nicotine/downloads
      - /home/pi/Appdata/nicotine/incomplete:/data/.local/share/nicotine/incomplete
      - /home/pi/Appdata/nicotine/received:/data/.local/share/nicotine/received
      - /home/pi/Appdata/nicotine/shares:/data/shares
    ports:
      - 6080:6080
    restart: unless-stopped
