FROM ubuntu:22.04

COPY ui.patch /tmp

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y python3 python3-pip python3-dev pkg-config ninja-build cmake \
    libgtk-3-dev binutils ca-certificates curl dbus gnupg2 \
    fonts-noto-cjk locales openbox patch supervisor \
    tigervnc-standalone-server tigervnc-tools tzdata \
    libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev \
    build-essential libglib2.0-dev libgirepository1.0-dev libgirepository-1.0-1 \
    gobject-introspection gir1.2-gobject-2.0 gir1.2-gtk-3.0 \
    python3-gi python3-gi-cairo python3-setuptools python3-wheel --no-install-recommends && \
    dbus-uuidgen > /etc/machine-id && \
    pip3 install --no-cache-dir meson ninja && \
    locale-gen en_US.UTF-8 && \
    mkdir -p /usr/share/novnc /usr/share/novnc/utils/websockify && \
    curl -fL# https://github.com/novnc/noVNC/archive/master.tar.gz -o /tmp/novnc.tar.gz && \
    tar -xf /tmp/novnc.tar.gz --strip-components=1 -C /usr/share/novnc && \
    curl -fL# https://github.com/novnc/websockify/archive/master.tar.gz -o /tmp/websockify.tar.gz && \
    tar -xf /tmp/websockify.tar.gz --strip-components=1 -C /usr/share/novnc/utils/websockify && \
    curl -fL# https://site-assets.fontawesome.com/releases/v6.0.0/svgs/solid/cloud-arrow-down.svg -o /usr/share/novnc/app/images/downloads.svg && \
    curl -fL# https://site-assets.fontawesome.com/releases/v6.0.0/svgs/solid/folder-music.svg -o /usr/share/novnc/app/images/shared.svg && \
    curl -fL# https://site-assets.fontawesome.com/releases/v6.0.0/svgs/solid/comments.svg -o /usr/share/novnc/app/images/logs.svg && \
    bash -c 'sed -i "s/<path/<path style=\"fill:white\"/" /usr/share/novnc/app/images/{downloads,logs,shared}.svg' && \
    patch /usr/share/novnc/vnc.html < /tmp/ui.patch && \
    sed -i 's/10px 0 5px/8px 0 6px/' /usr/share/novnc/app/styles/base.css && \
    pip3 install --no-cache-dir colorama && \
    pip3 install --no-cache-dir --no-deps nicotine-plus && \
    useradd -u 1000 -U -d /data -s /bin/false soulseek && \
    usermod -G users soulseek && \
    apt-get install -y nano && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /data/.config/nicotine

ARG CACHE_DATE

ADD ./configset.py /configset.py

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    XDG_RUNTIME_DIR=/data

COPY etc /etc
COPY usr /usr
COPY init.sh /init.sh

RUN chmod +x /init.sh

ENTRYPOINT ["/init.sh"]
