version: "3"
services:
  nicotine:
    image: hockeygoalie35/nicotine-novnc-rpi:latest
    container_name: nicotine
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /path/to/Nicotine/data:/data
      - /path/to/downloads:/data/.local/share/nicotine/downloads
      - /path/to/incomplete:/data/.local/share/nicotine/incomplete
      - /path/to/received:/data/.local/share/nicotine/received
      - /path/to/shares:/data/shares
    ports:
      - 6080:6080
    restart: unless-stopped
