FROM ubuntu:22.04
COPY ui.patch /tmp
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y python3-dev cmake libgtk-3-dev binutils ca-certificates curl dbus fonts-noto-cjk locales openbox patch supervisor tigervnc-standalone-server tigervnc-tools tzdata libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential libgirepository1.0 python3-pip --no-install-recommends
RUN dbus-uuidgen > /etc/machine-id && \
    locale-gen en_US.UTF-8 && \
    mkdir /usr/share/novnc && \
    curl -fL# https://github.com/novnc/noVNC/archive/master.tar.gz -o /tmp/novnc.tar.gz && \
    tar -xf /tmp/novnc.tar.gz --strip-components=1 -C /usr/share/novnc && \
    mkdir /usr/share/novnc/utils/websockify && \
    curl -fL# https://github.com/novnc/websockify/archive/master.tar.gz -o /tmp/websockify.tar.gz && \
    tar -xf /tmp/websockify.tar.gz --strip-components=1 -C /usr/share/novnc/utils/websockify && \
    curl -fL# https://site-assets.fontawesome.com/releases/v6.0.0/svgs/solid/cloud-arrow-down.svg -o /usr/share/novnc/app/images/downloads.svg && \
    curl -fL# https://site-assets.fontawesome.com/releases/v6.0.0/svgs/solid/folder-music.svg -o /usr/share/novnc/app/images/shared.svg && \
    curl -fL# https://site-assets.fontawesome.com/releases/v6.0.0/svgs/solid/comments.svg -o /usr/share/novnc/app/images/logs.svg && \
    bash -c 'sed -i "s/<path/<path style=\"fill:white\"/" /usr/share/novnc/app/images/{downloads,logs,shared}.svg' && \
    patch /usr/share/novnc/vnc.html < /tmp/ui.patch && \
    sed -i 's/10px 0 5px/8px 0 6px/' /usr/share/novnc/app/styles/base.css
RUN pip3 install meson ninja&& \
    pip3 install --no-cache-dir nicotine-plus colorama&& \
    useradd -u 1000 -U -d /data -s /bin/false soulseek && \
    usermod -G users soulseek
RUN mkdir -p /data/.config/nicotine
RUN apt-get install nano
ARG CACHE_DATE
ADD ./configset.py /configset.py
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    XDG_RUNTIME_DIR=/data
COPY etc /etc
COPY usr /usr
COPY init.sh /init.sh
RUN chmod +x /init.sh
RUN echo -e "\nADW_DEBUG_COLOR_SCHEME=prefer-dark" >> /etc/environment
ENTRYPOINT ["/init.sh"]
